// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://upvdeomgeezypmiyroua.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVwdmRlb21nZWV6eXBtaXlyb3VhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc5NjU3NTYsImV4cCI6MjA2MzU0MTc1Nn0.pEOinNAk1B9RnS9T4rhAJ-ncCw7Oong7quZYr38Kk7U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);